name: dataflow_wikimedia
version: "1.0.0"
config-version: 2

profile: dataflow_wikimedia

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  dataflow_wikimedia:
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: mart
      +materialized: table
